# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints2.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0/design_2_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_c_counter_binary_0_0/design_2_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_c_counter_binary_0_0 || ORIG_REF_NAME==design_2_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# XDC: e:/EclypseZ7/vivado24port/uart2_2019_1/uart2_2019_1.gen/sources_1/bd/design_2/design_2_ooc.xdc
