@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Mar 23 22:01:15 +0100 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FPGA_SPI_wrapper_behav -key {Behavioral:sim_1:Functional:FPGA_SPI_wrapper} -tclbatch FPGA_SPI_wrapper.tcl -protoinst "protoinst_files/FPGA_SPI.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
call xsim  FPGA_SPI_wrapper_behav -key {Behavioral:sim_1:Functional:FPGA_SPI_wrapper} -tclbatch FPGA_SPI_wrapper.tcl -protoinst "protoinst_files/FPGA_SPI.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
