@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 08 05:02:30 +0200 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim memory_manager_wrapper_behav -key {Behavioral:sim_1:Functional:memory_manager_wrapper} -tclbatch memory_manager_wrapper.tcl -protoinst "protoinst_files/memory_manager.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
call xsim  memory_manager_wrapper_behav -key {Behavioral:sim_1:Functional:memory_manager_wrapper} -tclbatch memory_manager_wrapper.tcl -protoinst "protoinst_files/memory_manager.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
